[package]
name = "binfft"
version = "0.1.0"
edition = "2021"

[dependencies]
num-complex = "0.4"
dyn-stack = "0.3"

[features]
default = []
nightly = []

[dev-dependencies]
criterion = "0.3"
rustfft = "6.0"
fftw-sys = { version = "0.6", default-features = false, features = ["system"] }
rand = "0.8"

[[bench]]
name = "fft"
harness = false
