[package]
name = "binfft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-complex = "0.4"
lazy_static = "1.4"
dyn-stack = "0.3"
seq-macro = "0.3"

[dev-dependencies]
criterion = "0.3"
rustfft = "6.0"
fftw-sys = { version = "0.6", default-features = false, features = ["system"] }
rand = "0.8"

[build-dependencies]
eyre = "0.6"

[[bench]]
name = "fft"
harness = false
