name: Test

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-benches:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install FFTW
        run: sudo apt install -y libfftw3-dev
      - name: Compile benches
        run: cargo bench --no-run

  cargo-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Test debug
        run: cargo test
      - name: Test debug serialization
        run: cargo test --features=serde
      - name: Test debug no-std
        run: cargo test --no-default-features

  cargo-tests-nightly:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Test debug nightly
        run: cargo test
