# Start all benchmark jobs on Slab CI bot.
name: Start all benchmarks

on:
  schedule:
    # Job will be triggered each Friday at 10p.m.
    - cron: '0 22 * * 5'
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  start-benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Slab repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          repository: zama-ai/slab
          path: slab
          token: ${{ secrets.CONCRETE_ACTIONS_TOKEN }}

      - name: Start AWS job in Slab
        shell: bash
        run: |
          echo -n '{"command": "bench", "git_ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}' > command.json
          SIGNATURE="$(slab/scripts/hmac_calculator.sh command.json '${{ secrets.JOB_SECRET }}')"
          curl -v -k \
          --fail-with-body \
          -H "Content-Type: application/json" \
          -H "X-Slab-Repository: ${{ github.repository }}" \
          -H "X-Slab-Command: start_aws" \
          -H "X-Hub-Signature-256: sha256=${SIGNATURE}" \
          -d @command.json \
          ${{ secrets.SLAB_URL }}
